name = "mybaseui"
type = "javascript"
account_id = "your-account-id"
workers_dev = true
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"